### ISSUE TITLE
【求助】fonts.xml 是空文件，CJK 字符显示为豆腐块。

### ISSUE THREAD

**Issue by k5746** [simonsmh/notocjk#1]
型号：Nexus 6
Android 版本：7.1.1
Magisk 版本：15.3

**Comment by simonsmh** [comment]
请上传详细日志，/system/etc/fonts.xml原始文件，/sbin/.core/img/.core/fonts.xml修改后的文件

**Comment by k5746** [comment]
1. 是哪部分的日志？安装时的？
2. 安装前，原始文件是正常的，有内容的。
[原始文件fonts.xml.txt](https://github.com/Magisk-Modules-Repo/magisk-notosanscjk-nougat/files/1639438/fonts.xml.txt)
3. 安装后，原始文件变成空的。而修改后的并没有生成。

**Comment by k5746** [comment]
[安装日志.txt](https://github.com/Magisk-Modules-Repo/magisk-notosanscjk-nougat/files/1640082/default.txt) 截取自 TWRP 导出的日志文件 recover.log。

**Comment by k5746** [comment]
v1.5 可以正常使用。

**Comment by simonsmh** [comment]
啊 我知道了
不好意思不好意思，我中午修一下

**Comment by simonsmh** [comment]
请试一下v1.6

**Comment by k5746** [comment]
v1.6 在 Magisk Manager 安装完成，重启后，magisk 显示正常，但 超级用户 及 模块 均失效，日志只有与
 Magisk Hide 相关的内容。

**Comment by k5746** [comment]
在 recovery 安装时 提示有错误。
[recovery.log.txt](https://github.com/Magisk-Modules-Repo/magisk-notosanscjk-nougat/files/1641544/recovery.log.txt)

**Comment by simonsmh** [comment]
好奇怪的表现。。
可以的话，能否尝试先完整卸载然后重装一下magisk呢？还有，我注意到你recovery log里出现了Segmentation fault又是recovery/magisk哪方面出现的问题呢？
此外，晚些时候我会尝试修复一下recovery安装的问题，但是从magisk manager安装应当是可以的。
感谢您帮助我并继续进行测试。

**Comment by k5746** [comment]
完全卸载并重装 Magisk v15.3 后，再在 Magisk Manager 安装 v1.6，情况依旧。
各 fonts.xml 均正常。

**Comment by k5746** [comment]
啊嘞啊嘞！开关一次 Magisk 核心功能模式 就可以了哎（包括重启）！
话说有什么办法可以查看字重的显示效果？我现在只能从零散的地方看到变化。

**Comment by simonsmh** [comment]
能看到变化就行了，细微之处见锋芒（
兼容Rec的部分我还要修改，issue暂且保留

**Comment by simonsmh** [comment]
@k5746 1.6.1修好了rec安装问题，请重新测试一下，谢谢

**Comment by k5746** [comment]
在 rec 安装后，又出现了豆腐块。
/magisk/.core/fonts.xml 正常。
/system/etc/fonts.xml 空白。
/magisk/notosanscjk-nougat/system/etc/fonts.xml 空白。
空白文件都链接到 /dev/tmp/magisk_img/.core/fonts.xml，但该路径已不存在。

**Comment by simonsmh** [comment]
修复好了，现在会链接到正确的位置了
请重新下载更新

**Comment by k5746** [comment]
可以了，在 rec 安装后显示正常。
