### ISSUE TITLE
MIUI10不能设置为全局字体

### ISSUE THREAD

**Issue by Measureless** [simonsmh/notocjk#10]
安装了模块，但是只有部分应用字体是Noto Sans CJK，而系统（及其自带应用）自带的字体依然是小米兰亭。
我安装的版本：
![image](https://user-images.githubusercontent.com/30423783/56636984-0c134980-669d-11e9-8086-7b41dad09160.png)
![image](https://user-images.githubusercontent.com/30423783/56636990-12a1c100-669d-11e9-9149-d97632600b3b.png)
知乎显示正常：
![image](https://user-images.githubusercontent.com/30423783/56637006-20efdd00-669d-11e9-9ce3-00d99dd96bca.png)

美团外卖显示正常：
![image](https://user-images.githubusercontent.com/30423783/56637201-a2476f80-669d-11e9-9ee1-8c083fbe6b8e.png)

系统和系统应用的界面，显示的是小米兰亭：
![image](https://user-images.githubusercontent.com/30423783/56637025-31a05300-669d-11e9-93c4-69c3917792ae.png)
![image](https://user-images.githubusercontent.com/30423783/56637115-67ddd280-669d-11e9-95ca-905be67afd4b.png)
![image](https://user-images.githubusercontent.com/30423783/56637181-952a8080-669d-11e9-97be-1c5ea4a88890.png)
![image](https://user-images.githubusercontent.com/30423783/56637234-ba1ef380-669d-11e9-8c2c-e9d9049bdf91.png)

锁屏界面还是小米兰亭：
![image](https://user-images.githubusercontent.com/30423783/56637033-36fd9d80-669d-11e9-89d2-7fb53facf70e.png)

锁屏输入密码这里是Noto Sans CJK：
![image](https://user-images.githubusercontent.com/30423783/56637042-3bc25180-669d-11e9-9c03-e2cffc5bfacf.png)

微信显示则是两种字体混用：
![image](https://user-images.githubusercontent.com/30423783/56637304-e5094780-669d-11e9-9035-7f833ead2355.png)
![image](https://user-images.githubusercontent.com/30423783/56637313-eaff2880-669d-11e9-8606-8cd22a9a5c26.png)

PS：状态栏显示的也是小米兰亭

**Comment by simonsmh** [comment]
MIUI sucks. 因为有MIUI主题适配原因，字体其实是不方便修改的。
将就用用吧。MIUI国际版是正常的。

**Comment by moposx** [comment]
因为MIUI国内版的`fonts.xml`添加了小米兰亭的配置，如果你想用新字体全局替换掉小米兰亭，就需要去掉这段配置。
```xml
    <!-- MIUI ADD: Begin /-->
    <family name="miui">
        <font weight="100" style="normal">Miui-Thin.ttf</font>
        <font weight="300" style="normal">Miui-Light.ttf</font>
        <font weight="400" style="normal">Miui-Regular.ttf</font>
        <font weight="700" style="normal">Miui-Bold.ttf</font>
    </family>

    <alias name="miui-thin" to="miui" weight="100" />
    <alias name="miui-light" to="miui" weight="300" />
    <alias name="miui-bold" to="miui" weight="700" />

    <family name="miuiex">
        <font weight="400" style="normal">MiuiEx-Regular.ttf</font>
        <font weight="700" style="normal">MiuiEx-Bold.ttf</font>
    </family>
    <family name="miuiex-light">
        <font weight="300" style="normal">MiuiEx-Light.ttf</font>
    </family>
    <!-- MIUI ADD: End /-->
```
此外，对于自带应用，不少自带都带有自己的字体，无法保证在这些app中正常显示你希望替换的字体（不过这类自带大都是体积很小的字体，用以显示总数量较少的数字和字母等部分字符）。但是，MIUI论坛app自带了全量的小米兰亭regular字重的字体，因此替换字体不会对这个app生效。
