### ISSUE TITLE
请教关于修改 index 无用的问题

### ISSUE THREAD

**Issue by WhiverFichos** [simonsmh/notocjk#15]
我把 fonts.xml 中的 "zh-Hant" "zh-Hant zh-Bopo" 下的 index 修改为 1（"ko"），但是似乎刷入后没有此效果（和修改 index 前的效果一样，繁体中文下未使用韩国字形）。
请问这是什么原因呢？
Redmi Note 8 Pro
MIUI Global 11.0.3
Android 9

**Comment by simonsmh** [comment]
小米的手机会使用小米兰亭Pro，可能你看到的字体并非 Noto CJK，请试试在 Chrome 底下查看字体

**Comment by WhiverFichos** [comment]
我确定不是小米兰亭（国际版，fonts 文件夹和 fonts.xml 都没有；notocjkTW 真的明显），而且是全字重。
Chrome 查看字体什么操作（？
我瞎猜是不是字体内也写了语言代码，调用的时候直接看了那个，index 就没起作用（

**Comment by simonsmh** [comment]
那将系统语言切到韩文呢？应用自身的语言也可能会影响使用的字形。
此外，fonts.xml在/system/etc，修改请到/sbin/.magisk/modules/notocjk/system/etc，也请再检查一下

**Comment by WhiverFichos** [comment]
确认两边都是改了的样子。/etc 也一样（这个文件夹和 /system/etc 有什么关系？）。
不论是系统语言还是浏览器中的相应语言，效果都和没改一样。系统语言切换到韩文自然系统的字形是 KR，但在繁体中文网页上，还是 TW 字形。
把繁体中文下的 index 改掉了，应用的语言即使是繁体中文还会使用 TW 字形？TW 字形不应该直接出不来吗？
香港繁体和台湾繁体的区别是不是没有在 fonts.xml 体现？但是在这两种语言下，字形不同。
作为对照，只把字体拷到 /system/fonts 中而不修改没有效果。

**Comment by simonsmh** [comment]
1. 我觉得应该是没有完全更改的原因，如果还想尝试的话建议直接更改模块压缩包内的[customize.sh](https://github.com/Magisk-Modules-Repo/notocjk/blob/master/customize.sh#L11,L18)文件。
将L11到L18范围的`index="3"`替换为`index="1"`，然后重新刷入，而不是直接修改`fonts.xml`。
2. 香港繁体和台湾繁体暂时不知道如何区分修改，因为Google直到Android R为止自己也没有使用香港繁体，香港字体是`index="4"`
3. 字体应该是不会有问题的，5种字形都有，韩文确实是`index="1"`，可以拿`otc2otf.py`脚本检查offset
```
Input font: system/fonts/NotoSansCJK-Black.ttc
Version: 65536.  numFonts: 5.
font 0 offset: 32/0x00000020. NotoSansCJKjp-Black
font 1 offset: 300/0x0000012C. NotoSansCJKkr-Black
font 2 offset: 568/0x00000238. NotoSansCJKsc-Black
font 3 offset: 836/0x00000344. NotoSansCJKtc-Black
font 4 offset: 1104/0x00000450. NotoSansCJKhk-Black
```

**Comment by WhiverFichos** [comment]
1. 我就是这么改的。
2. 修改前后，语言为港/台时字形都不同（修改前是字重不全的思源黑体）。这是 MIUI 在别处儿加的特性，没改到？还有什么地方可能有字体定义文件？

**Comment by simonsmh** [comment]
应该只有fonts.xml，方便的话你可以提取一份发到这里

**Comment by WhiverFichos** [comment]
是不支持 xml 文件吗
[fonts.txt](https://github.com/Magisk-Modules-Repo/notocjk/files/4406686/fonts.txt)
前两组替换前是 Miui-Regular.ttf，fonts 文件夹中没有。

**Comment by simonsmh** [comment]
看起来没有任何问题，要不试试把zh-Hans和jp也换了？

**Comment by WhiverFichos** [comment]
一样，还是没用。只能单独放字体了？
另外，解压修改后再压缩为 zip 文件似乎 Magisk 不识别其为模块，只能在压缩文件改，这是为什么？

**Comment by simonsmh** [comment]
压缩包要求符合可刷入zip的标准，可能你把文件夹打包进压缩文件了

**Comment by WhiverFichos** [comment]
好吧，感谢解答问题~
最后祝您身体健康（
