### ISSUE TITLE
安装失败求助

### ISSUE THREAD

**Issue by ShadowySpirits** [simonsmh/notocjk#16]
手机：OnePlus 7T pro
系统：Android 10
Magisk 版本：20.4

安装流程：
因 magisk 仓库中搜不到对应的模块，我下载源码打包成 zip 然后安装

报错：
```
- Copying zip to temp directory
- Installing notocjk.zip
! Installation failed
```

**Comment by simonsmh** [comment]
1. 你需要将目录重新拆装成符合Android zip格式的目录结构，具体来说就是先解压zip后再将解压得到的文件夹中的内容再次压缩。
2. 我刚刚才注意到模块被下架了，应该因为是字体模块的原因，稍候我自己上传一份到release进行分发。

**Comment by simonsmh** [comment]
https://github.com/Magisk-Modules-Grave/notocjk/releases/
