### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by RiwiHow** [simonsmh/notocjk#17]
使用的是 Releases 下的模块。

* Redmi Note 7 Pro
* Android 10
* Magisk 20.4

![](https://global.cdn.mikupics.cn/2020/04/21/90c9c01f47853.png)

**Comment by simonsmh** [comment]
我忘记替换[module_installer.sh](https://github.com/topjohnwu/Magisk/blob/master/scripts/module_installer.sh)了，抱歉

**Comment by simonsmh** [comment]
测试过可以刷入了，请重新下载一下。
