### ISSUE TITLE
DemiLight的可调用性

### ISSUE THREAD

**Issue by WordlessEcho** [simonsmh/notocjk#18]
在API28以下的系统中，`TextView`调用不同字重的字体所使用的属性是[fontFamily](https://developer.android.com/reference/android/widget/TextView#attr_android:fontFamily)。`fontFamily`的属性值则使用了[fonts.xml中的alias](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/android10-c2f2-s2-release/data/fonts/fonts.xml#40)。

在系统默认的alias中，是没有DemiLight的。也就是说，不使用API28以后提供的[textFontWeight](https://developer.android.com/reference/android/widget/TextView#attr_android:textFontWeight)，DemiLight实际上是无法被程序调用的。

问题：
1. 应不应当为Noto Sans CJK加入DemiLight的alias？
2. `fallbackFor`属性与`textFontWeight`是同期推出的，Noto Serif CJK是不是没有必要再添加alias（视作为历史遗留）？

**Comment by simonsmh** [comment]
如果调用不在配置中的字重值，系统会选择如何渲染？在字重选择上，原本的计划就是不考虑设备占用，谷歌给多少字体就用多少字体，其实对于想看出全字重来说拿3个字体就够了。

Noto Serif CJK似乎没有有更好的应用方法了，为在实际使用中几乎看不见效果而头疼也不是一天两天了，如果有更好的应用方法也可以提出。

**Comment by WordlessEcho** [comment]
> 如果调用不在配置中的字重值，系统会选择如何渲染？
- `fontFamily`：系统会按照regular渲染
- `textFontWeight`：系统用不知道什么黑魔法渲染

**Comment by simonsmh** [comment]
已移除DemiLight字重

**Comment by WordlessEcho** [comment]
既然用了variable font，那要把DemiLight加回去吗？
关于DemiLight可以看这个：[思源黑体的 DemiLight / Normal 字重因何而生？ - 孫志貴的回答 - 知乎](https://www.zhihu.com/question/24607502/answer/28362461)

**Comment by simonsmh** [comment]
主要原因就是系统无法合理调用，textFontWeight渲染可变字体也符合效果，因此之后绝对不再考虑添加了。对于sans-serif保留100 300 400 500 700 900已经足够了，serif尤甚，只需400和700即可满足默认alias。当然由于现在可变字体尚未完善，临时加回来也是可以的。

**Comment by WordlessEcho** [comment]
没关系，不加回来就不加回来了
