### ISSUE TITLE
部分emoji显示不正常

### ISSUE THREAD

**Issue by WhiCCX0** [simonsmh/notocjk#21]
![Screenshot_20210403-140029~01](https://user-images.githubusercontent.com/47388635/113470053-3410a780-9485-11eb-9d7b-40884adc88e7.png)
![Screenshot_20210403-140005~01](https://user-images.githubusercontent.com/47388635/113470055-36730180-9485-11eb-9f9c-4b440d4b43c6.png)
如图所示，安卓11

**Comment by WordlessEcho** [comment]
参见： https://github.com/simonsmh/notocjk/issues/22#issuecomment-818671042

Workaround: 将400 weight换回系统自带的版本，详见 #22
