### ISSUE TITLE
Noto Sans CJK支持variable font

### ISSUE THREAD

**Issue by WordlessEcho** [simonsmh/notocjk#22]
https://github.com/googlefonts/noto-cjk/tree/main/Sans/Variable

**Comment by simonsmh** [comment]
参考wght值是多少？

**Comment by WordlessEcho** [comment]
我只知道Source Han Sans有文档，第十页，关键词weights
https://github.com/adobe-fonts/source-han-sans/blob/release/SourceHanSansReadMe.pdf

**Comment by WordlessEcho** [comment]
```bash
# SC as a example. They were same.
ttx -y 3 -t fvar NotoSansCJK-VF.ttc
```
```xml
  <fvar>

    <!-- Weight -->
    <Axis>
      <AxisTag>wght</AxisTag>
      <Flags>0x0</Flags>
      <MinValue>100.0</MinValue>
      <DefaultValue>100.0</DefaultValue>
      <MaxValue>900.0</MaxValue>
      <AxisNameID>265</AxisNameID>
    </Axis>

    <!-- Thin -->
    <!-- PostScript: NotoSansCJKscVF-Thin -->
    <NamedInstance flags="0x0" postscriptNameID="267" subfamilyNameID="266">
      <coord axis="wght" value="100.0"/>
    </NamedInstance>

    <!-- Light -->
    <!-- PostScript: NotoSansCJKscVF-Light -->
    <NamedInstance flags="0x0" postscriptNameID="269" subfamilyNameID="268">
      <coord axis="wght" value="300.0"/>
    </NamedInstance>

    <!-- DemiLight -->
    <!-- PostScript: NotoSansCJKscVF-DemiLight -->
    <NamedInstance flags="0x0" postscriptNameID="271" subfamilyNameID="270">
      <coord axis="wght" value="350.0"/>
    </NamedInstance>

    <!-- Regular -->
    <!-- PostScript: NotoSansCJKscVF-Regular -->
    <NamedInstance flags="0x0" postscriptNameID="273" subfamilyNameID="272">
      <coord axis="wght" value="400.0"/>
    </NamedInstance>

    <!-- Medium -->
    <!-- PostScript: NotoSansCJKscVF-Medium -->
    <NamedInstance flags="0x0" postscriptNameID="275" subfamilyNameID="274">
      <coord axis="wght" value="500.0"/>
    </NamedInstance>

    <!-- Bold -->
    <!-- PostScript: NotoSansCJKscVF-Bold -->
    <NamedInstance flags="0x0" postscriptNameID="277" subfamilyNameID="276">
      <coord axis="wght" value="700.0"/>
    </NamedInstance>

    <!-- Black -->
    <!-- PostScript: NotoSansCJKscVF-Black -->
    <NamedInstance flags="0x0" postscriptNameID="279" subfamilyNameID="278">
      <coord axis="wght" value="900.0"/>
    </NamedInstance>
  </fvar>
```

Tools: [fonttools/fonttools: A library to manipulate font files from Python.](https://github.com/fonttools/fonttools)
See also: [fvar — Font Variations Table (OpenType 1.8.4) - Typography | Microsoft Docs](https://docs.microsoft.com/en-us/typography/opentype/spec/fvar#instancerecord)

**Comment by simonsmh** [comment]
联动 #25 #21 
v11 替换 NotoSansCJK Regular 字重后，在多字重效果仍在的同时， #25 的符号正常显示了，但也复现了 #21 的问题。这应该是VF字形缺失了部分字符，或是正常字形包含了不应该包含的字符导致的，但有没有什么更好的办法能临时解决这个问题？

**Comment by WordlessEcho** [comment]
> 联动 #25 #21
> v11 替换 NotoSansCJK Regular 字重后，在多字重效果仍在的同时， #25 的符号正常显示了，但也复现了 #21 的问题。这应该是VF字形缺失了部分字符，或是正常字形包含了不应该包含的字符导致的，但有没有什么更好的办法能临时解决这个问题？

> VF字形缺失了部分字符

应该不是，可能是配置上的bug
我举个例子 ●（U+25CF）
```xml
<map code="0x25cf" name="H18533"/><!-- BLACK CIRCLE -->
```
有是有的，但是只有VF显示不出来这个字符，super OTC的就正常

> 正常字形包含了不应该包含的字符导致的

不仅是常规版本，VF版也有这个问题
再举一个例子 🆓（U+1F193）
2.003版本Noto Sans CJK (super OTC)
```xml
<map code="0x1f193" name="cid59356"/><!-- SQUARED FREE -->
```
从Android 11上复制出来的2.001版本Noto Sans CJK Regular (OTC)没有这个字符

**Comment by WordlessEcho** [comment]
我刚刚试着把这两行放到比CJK更前的位置，但是没有用，所以我能想到的唯一办法就是重新编译字体了。
```xml
    <family lang="und-Zsye">
        <font weight="400" style="normal">NotoColorEmoji.ttf</font>
    </family>
    <family lang="und-Zsym">
        <font weight="400" style="normal">NotoSansSymbols-Regular-Subsetted2.ttf</font>
    </family>
```

**Comment by WordlessEcho** [comment]
我刚刚测试了一下，如果把模块里的NotoSansCJK-Regular.ttc删掉，#21 就正常了

**Comment by WordlessEcho** [comment]
最后的结论是，Android里的NotoSansCJK-Regular.ttc和[noto-cjk](https://github.com/googlefonts/noto-cjk)上的是不一样的。如果要避免 #21 的问题，就是每次都修改字体，把这些特定的字符删掉

详见： https://github.com/googlefonts/noto-cjk/issues/191#issuecomment-818668353

**Comment by WordlessEcho** [comment]
搜索了一下，这是AOSP修改字体用的代码
https://android.googlesource.com/platform/external/noto-fonts/+/refs/heads/master/cjk/subset_noto_cjk.py

**Comment by simonsmh** [comment]
感觉nototools有点bug，这个脚本没办法成功跑

**Comment by WordlessEcho** [comment]
因为这段代码有点Python 2的历史，又缺乏维护，我修改了三处因为Python 3改动出现的问题，目前正在执行

**Comment by WordlessEcho** [comment]
明天会想办法把改过的`subset_noto_cjk.py`发出来，当然就算改过了还是有一些问题，不过影响不是很大，暂时没什么余力修。
大概会考虑修改成一个能用的工具再发布出来？还没想好用什么软件协议

**Comment by simonsmh** [comment]
新的commit中，还是不要额外修改字体文件名比较好吧，这样可以直接对原文件进行替换来避免重复字体名产生冲突

**Comment by WordlessEcho** [comment]
> 新的commit中，还是不要额外修改字体文件名比较好吧，这样可以直接对原文件进行替换来避免重复字体名产生冲突

行，但是麻烦你看一下actions，我好像没法用自动release？

**Comment by simonsmh** [comment]
> > 新的commit中，还是不要额外修改字体文件名比较好吧，这样可以直接对原文件进行替换来避免重复字体名产生冲突
> 
> 行，但是麻烦你看一下actions，我好像没法用自动release？

action需要签tag才会自动release，等新版本准备好时我来签tag

**Comment by WordlessEcho** [comment]
那你测试一下，我都弄好了

**Comment by WordlessEcho** [comment]
variable版本传错了，传成了remove codepoints但还没加chws的版本

**Comment by vvb2060** [comment]
https://issuetracker.google.com/issues/186033995
