### ISSUE TITLE
Serif字体除regular和bold都无法被调用

### ISSUE THREAD

**Issue by WordlessEcho** [simonsmh/notocjk#23]
看起来和英文只有regular和bold字重这回事也有关系
![Screenshot_20210410-020910_Font_Provider](https://user-images.githubusercontent.com/12007025/114223208-1d48e400-99a2-11eb-9fa5-44a6c8271be2.png)

**Comment by WordlessEcho** [comment]
我猜测如果把英文那部分的字重补全就能调用了，明天试一下
https://github.com/googlefonts/noto-fonts/tree/main/hinted/ttf/NotoSerif

**Comment by WordlessEcho** [comment]
我翻了一下[FontProvider的源码](https://github.com/RikkaApps/FontProvider/blob/8c83da6b2e1061d3ef2f078f010c1b72994c6056/app/src/main/java/moe/shizuku/fontprovider/PreviewActivity.java#L91)
```java
                textSerif100.setTypeface(Typeface.create("serif-thin", Typeface.NORMAL));
```

总之遇到的问题和 #18 是一样的，设置的如果是`textFontWeight`就正常

**Comment by simonsmh** [comment]
其实说白了，除了rikka没人用这么多字重，是谷歌的问题。= - =
