### ISSUE TITLE
可变字体版本部分符号显示不了

### ISSUE THREAD

**Issue by AokiFuru** [simonsmh/notocjk#25]
使用了可变字体版本后一部分符号显示不了 图为 gboard 日语输入符号页面。
版本8：
![Screenshot_20210411-132507~2](https://user-images.githubusercontent.com/50285380/114293307-fe487000-9acf-11eb-8d4f-9e75406b2d8e.jpg)
版本10：
![Screenshot_20210411-141018~2](https://user-images.githubusercontent.com/50285380/114293308-00aaca00-9ad0-11eb-92f5-d9ac71a5a713.jpg)

**Comment by WordlessEcho** [comment]
Workaround: 将400 weight换回系统自带的版本，详见 #22

**Comment by WordlessEcho** [comment]
已提交到上游 adobe-fonts/source-han-sans#296
