### ISSUE TITLE
一些浏览器不能正确调用variable font

### ISSUE THREAD

**Issue by WordlessEcho** [simonsmh/notocjk#28]
短暂地出现在v10版本，可见 WordlessEcho/Noto-CJK-VF-Magisk#2

## Firefox
在本模块表现为字体fallback到了Droid Sans Fallback
![Screenshot_20210412-013904_Firefox_Nightly](https://user-images.githubusercontent.com/12007025/114315590-36809a80-9b32-11eb-80d1-88743cd489b5.png)

注意这个「局」字
![Screenshot_20210412-013913_Firefox_Nightly](https://user-images.githubusercontent.com/12007025/114315605-45674d00-9b32-11eb-8e26-c2007a2db2fc.png)

在Noto Sans CJK SC里，局字是这样的
![局 in Noto Sans SC](https://user-images.githubusercontent.com/12007025/114315633-60d25800-9b32-11eb-9cec-c8308454826f.png)

## 淘宝和QQ内置的WebView
参见 WordlessEcho/Noto-CJK-VF-Magisk#6

## 明日方舟
参见 WordlessEcho/Noto-CJK-VF-Magisk#2

**Comment by WordlessEcho** [comment]
Close because this module did a workaround.

**Comment by WordlessEcho** [comment]
[1710512 - Support variable font for CJK](https://bugzilla.mozilla.org/show_bug.cgi?id=1710512)

~mozilla-mobile/fenix#19438~

**Comment by rhjdvsgsgks** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1710513#c12
~好像上游修了~
不包括 cjk

**Comment by noahhhi** [comment]
Xperia 1 III用了模块Firefox默认字体会特别细。
NotoCJK
![Screenshot_20210706-211833](https://user-images.githubusercontent.com/29367133/124608609-704b0e00-dea1-11eb-9a10-9d017b323c61.png)
默认
![Screenshot_20210706-211941](https://user-images.githubusercontent.com/29367133/124607942-e307b980-dea0-11eb-9c01-5b6ce335597a.png)
和上次一样先传了font.xml：）
[NotoCJK](https://drive.google.com/file/d/1Zb5wYXTNahSY-Ysko7N1Zx0mxjYggOHe/view?usp=drivesdk) 
[Default](https://drive.google.com/file/d/1awRpL9RUtZ-jwkhFGatSaQyV084-pcU0/view?usp=drivesdk)

**Comment by simonsmh** [comment]
@noahhhi Firefox很快就会修复这个问题了，在这之前请使用[release 9u4](https://github.com/simonsmh/notocjk/releases/tag/9u4)。

**Comment by nexplorer-3e** [comment]
不确定是不是 lineage 的 fonts.xml 没写其他 lang 的缘故，在访问主要语言不为简中的网页（如 github）时会使用 jp 字型。
lineage 22.2 (android 15), `munch`:

![Image](https://github.com/user-attachments/assets/e9db7e91-6369-4232-ae70-47e794079a5f)
访问简中网页（如 baidu）时没有这个问题：

![Image](https://github.com/user-attachments/assets/15fbdf9a-84d0-43ff-81f6-32d879e6bc2d)

[cjkbakxml.zip](https://github.com/user-attachments/files/19926288/cjkbakxml.zip)
