### ISSUE TITLE
11版本无可变字重效果

### ISSUE THREAD

**Issue by cccClyde** [simonsmh/notocjk#29]
使用这个 App 测试：https://github.com/WordlessEcho/Variable-Font-Test

测试效果如图，仅英文有效：![Screenshot_20210414-005806.png](https://user-images.githubusercontent.com/34314096/114591684-bb97bb00-9cbc-11eb-9049-c9cf73b20b33.png)

**Comment by WordlessEcho** [comment]
因为VF版有字符显示上的问题，本模块的regular字重使用了常规版本的字体（NotoSansCJK-Regular.ttc version 2.003 from [noto-cjk](https://github.com/googlefonts/noto-cjk)），故系统无法正确调用variable font特性
详情请见 #25 和 adobe-fonts/source-han-sans#296

**Comment by WordlessEcho** [comment]
您如果愿意承担以下问题： WordlessEcho/Noto-CJK-VF-Magisk#2 WordlessEcho/Noto-CJK-VF-Magisk#5
可以尝试这个模块 [WordlessEcho/Noto-CJK-VF-Magisk](https://github.com/WordlessEcho/Noto-CJK-VF-Magisk)

**Comment by WordlessEcho** [comment]
我能额外请求一件事吗？可以麻烦你把Android 12原本的fonts.xml发出来看看吗？
因为Android 11的英文字体（Roboto）是不支持variable font的，按照你的描述，Google在Android 12上使用了Roboto VF？

**Comment by cccClyde** [comment]
> 我能额外请求一件事吗？可以麻烦你把Android 12原本的fonts.xml发出来看看吗？
> 因为Android 11的英文字体（Roboto）是不支持variable font的，按照你的描述，Google在Android 12上使用了Roboto VF？

1. Noto-CJK-VF-Magisk 在 Android 12 确实有效，中英都有可变字重效果。
2. 卸载了所有字体模块，但在 /system_ext/etc 目录下竟然没有找到 Android 12 的 font.xml 文件（我记得之前在这里）。
3. 卸载了所有字体模块后测试了下，Android 12 使用了 Roboto VF：
![Screenshot_20210414-082758](https://user-images.githubusercontent.com/34314096/114637462-01c03f00-9cfc-11eb-88c2-52d87a84a8ae.png)

**Comment by cccClyde** [comment]
> 我能额外请求一件事吗？可以麻烦你把Android 12原本的fonts.xml发出来看看吗？
> 因为Android 11的英文字体（Roboto）是不支持variable font的，按照你的描述，Google在Android 12上使用了Roboto VF？

抱歉，找到了，这是没有启用任何第三方字体模块时 Android 12 默认的 font.xml（GitHub 不支持 .xml 上传，下载后去掉 .zip 后缀）：
[fonts.xml.zip](https://github.com/simonsmh/notocjk/files/6307427/fonts.xml.zip)

**Comment by WordlessEcho** [comment]
Reopen issue for tracking.

**Comment by simonsmh** [comment]
https://t.me/magiskalpha/297
请麻烦看看vf字体会不会造成影响？

**Comment by cccClyde** [comment]
> https://t.me/magiskalpha/297
> 请麻烦看看vf字体会不会造成影响？

有的，我目前遇到的主要就是使用 VF 模块会导致 Play 商店在搜索应用时闪退，之前排除了好久才得出的结论。卸载所有字体模块就不会有问题。

**Comment by vvb2060** [comment]
应该是Play商店在搜索时打开了gms的界面，你可以试试取消hide `com.google.android.gms/com.google.android.gms`

**Comment by cccClyde** [comment]
Hello，最近发现 kdrag0n 的 inter font 字体模块（也是可变字重）在 Android 12 + MagiskHide 的情况下竟然不会导致闪退，有兴趣看一下吗？https://github.com/kdrag0n/inter-font-pack/releases/tag/v3.19.0

**Comment by cccClyde** [comment]
> 应该是Play商店在搜索时打开了gms的界面，你可以试试取消hide `com.google.android.gms/com.google.android.gms`



> https://t.me/magiskalpha/297
> 请麻烦看看vf字体会不会造成影响？

Hello，最近发现 kdrag0n 的 inter font 字体模块（也是可变字重）在 Android 12 + MagiskHide 的情况下竟然不会导致闪退，有兴趣看一下吗？https://github.com/kdrag0n/inter-font-pack/releases/tag/v3.19.0

**Comment by WordlessEcho** [comment]
> > 应该是Play商店在搜索时打开了gms的界面，你可以试试取消hide `com.google.android.gms/com.google.android.gms`
> 
> > https://t.me/magiskalpha/297
> > 请麻烦看看vf字体会不会造成影响？
> 
> Hello，最近发现 kdrag0n 的 inter font 字体模块（也是可变字重）在 Android 12 + MagiskHide 的情况下竟然不会导致闪退，有兴趣看一下吗？https://github.com/kdrag0n/inter-font-pack/releases/tag/v3.19.0

它直接替换了系统字体，这样就不会「找不到字体」了

**Comment by WordlessEcho** [comment]
@simonsmh 我们要考虑将字体文件名命名为系统已有的文件名吗？
我在想这种方法还能不能替换Play商店里的字体，但是起码不闪退了

**Comment by simonsmh** [comment]
@WordlessEcho 我lite版本已经换为系统内自带字体的文件名了，有进一步的反馈吗？其他版本真的不方便做更换了

**Comment by cccClyde** [comment]
> @WordlessEcho 我lite版本已经换为系统内自带字体的文件名了，有进一步的反馈吗？其他版本真的不方便做更换了

嗯我这里试了下 lite 版本确实没有闪退现象了，在 Google 官方内置 CJK VF 之前应该可以满足使用需要，谢谢！

**Comment by WordlessEcho** [comment]
As [Magisk Hide ending its mission](https://topjohnwu.medium.com/state-of-magisk-2021-fe29fdaee458), this issue can be closed now.
