### ISSUE TITLE
Android 12开启Magisk Hide及本模块后闪退

### ISSUE THREAD

**Issue by FAST0888** [simonsmh/notocjk#33]

**Comment by WordlessEcho** [comment]
你对微信启用了Magisk Hide吗？

**Comment by FAST0888** [comment]
是的，Hide 里面只要启用的都会闪退，但是往往Hide里面的程序也是很重要的一些也是经常使用的

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by WordlessEcho** [comment]
由于Android 12的一些变化，开启Magisk Hide会导致系统无法找到我们更名后的字体文件，详见此处：
- https://github.com/simonsmh/notocjk/issues/29#issuecomment-824596761
- https://t.me/magiskalpha/297

解决方法有两种：
1. 关闭Magisk Hide。Magisk自引入Zygisk以来，就正式终止了Magisk Hide的支持：
[State of Magisk: 2021 | by topjohnwu | Medium](https://topjohnwu.medium.com/state-of-magisk-2021-fe29fdaee458)
2. 使用lite版本（旧版）：
https://github.com/simonsmh/notocjk/releases/tag/14_lite

**Comment by WordlessEcho** [comment]
I would keep this issue open. Let me know if you have any advices about the support of Magisk Hide. Maybe we should change the font name or keep updating lite version for compatibility?

**Comment by imbroglo** [comment]
你好，测试了下发现把字体文件更改为系统同名文件可以进入 Magisk Hide 里的微信，即改成 `NotoSansCJK-Regular.ttc` 和 `NotoSerifCJK-Regular.ttc`（在 `customize.sh` 脚本中更改的）。Magisk 版本为 23000，Android 12。

**Comment by WordlessEcho** [comment]
@FAST0888 @imbroglo 
尝试一下这个版本？看看能不能顺便解决你们的问题

~~[use static version for regular · simonsmh/notocjk@e1d13cb](https://github.com/simonsmh/notocjk/actions/runs/1732685034)~~
~~[make static regular as fallback · simonsmh/notocjk@b6daa5e](https://github.com/simonsmh/notocjk/actions/runs/1732921042)~~

[Release 20 · simonsmh/notocjk](https://github.com/simonsmh/notocjk/releases/tag/20)

**Comment by FAST0888** [comment]
21Lite  good...

**Comment by WordlessEcho** [comment]
请使用lite版。
Use lite version instead.

https://github.com/simonsmh/notocjk/releases

**Comment by FAST0888** [comment]
20 Bump version 可否使用? Magisk Hide 里的程序?

**Comment by WordlessEcho** [comment]
你试试？我这的Magisk已经没有Magisk Hide了

**Comment by FAST0888** [comment]
您的这个Magisk 是什么版本?  原来的Magisk 怎么替换?
两个有何区别?求教

**Comment by WordlessEcho** [comment]
我用的canary通道的Magisk，不适合日用，不建议你换

**Comment by tpnonthealps** [comment]
使用Shamiko替換MagiskHide可解決此問題。
