### ISSUE TITLE
（建议）Regular字重不使用可变字体（使用自带的NotoCJK文件）

### ISSUE THREAD

**Issue by RayChanNya** [simonsmh/notocjk#34]
将字重400的NotoCJK由可变字体版本更换为安卓自带的NotoCJK-Regular.ttc后可以在不增加模块大小的情况下解决部分兼容性问题，如图
![Screenshot_20220116-215435_Firefox](https://user-images.githubusercontent.com/47655274/149664005-a8b964ef-15c7-4060-b227-d54cb57c5df0.png)
![Screenshot_20220116-213616_Firefox](https://user-images.githubusercontent.com/47655274/149664007-f1e26433-43c9-4eb5-97bb-1b690fdd394b.png)
例如：
原costomize.sh的Regular字重写法：
<font weight="400" style="normal" index="2" postScriptName="NotoSansCJKsc-Regular">NotoSansCJK-VF.otf.ttc<axis tag="wght" stylevalue="400" \/><\/font>\n
更改后（参考了谷歌在安卓12中对Roboto VF的调用）
<font weight="400" style="normal">NotoSansCJK-Regular.ttc<\/font>\n

仅需要更改Regular字重，其他不改变
参考了Google对Roboto VF的处理（如下图）
![Screenshot_20220116-223803_Root Explorer](https://user-images.githubusercontent.com/47655274/149664638-6a7f9c3f-0682-4f4c-a439-40f7953c1c8f.png)

**Comment by RayChanNya** [comment]
被Github吞了例子前半段，大佬应该能看懂叭（

**Comment by RayChanNya** [comment]
例子部分转义符和前半段被Github吞了，忘记用Quote了....大佬应该能理解我的意思叭

**Comment by WordlessEcho** [comment]
#28 我觉得Mozilla应该不打算修这个问题，或许模块真的应该早做打算

**Comment by RayChanNya** [comment]
> #28 我觉得Mozilla应该不打算修这个问题，或许模块真的应该早做打算

毕竟跟着谷歌走（划掉

**Comment by WordlessEcho** [comment]
> > #28 我觉得Mozilla应该不打算修这个问题，或许模块真的应该早做打算
> 
> 毕竟跟着谷歌走（划掉

不一定的，有些小语种就没做兼容，最后还是我和Mozilla说了他们才知道

**Comment by RayChanNya** [comment]
> > > #28 我觉得Mozilla应该不打算修这个问题，或许模块真的应该早做打算
> > 
> > 
> > 毕竟跟着谷歌走（划掉
> 
> 不一定的，有些小语种就没做兼容，最后还是我和Mozilla说了他们才知道

我是指模块跟着谷歌走，不在regular这种字体上用可变字体（虽然谷歌好像除了roboto没这么干过）

**Comment by RayChanNya** [comment]
或者像lgxw的字体模块一样，后面加fallback

`（在此之前是可变字体的family）<family lang="zh-Hans,zh-Hant,zh-Bopo,JP,ko">\n<font weight="400" style="normal">NotoSansCJK-Regular.ttc<\/font>\n<\/family>`

**Comment by RayChanNya** [comment]
而且怎么说呢，像这种在可变中文的family之后再加一个不可变中文的family，好像能解决 #29 的问题，因为按安卓的优先级会优先调用可变字体，在不能用可变字体的情况下fallback到不可变字体（例如火狐）

**Comment by RayChanNya** [comment]
@WordlessEcho 我按照刚刚说的思路写了一个大概的版本，是我魔改的OPPO Sans，大佬凑合着看吧
https://rayhere.lanzouw.com/iS4yZyvltej

**Comment by simonsmh** [comment]
之前模块试过的方案也是直接替换400，但会字重无效来着

**Comment by WordlessEcho** [comment]
regular下会没法使用可变字体特性，调用粗体之后再调就行了，这点和Roboto一样。我一会加个fallback试试

**Comment by simonsmh** [comment]
还是采用后面加fallback的方案吧

**Comment by WordlessEcho** [comment]
测试好了，要不要给Roboto也弄一份？

https://github.com/simonsmh/notocjk/commit/b6daa5ed46da1613576035b904739850452804ef

**Comment by RayChanNya** [comment]
> 测试好了，要不要给Roboto也弄一份？
> 
> [b6daa5e](https://github.com/simonsmh/notocjk/commit/b6daa5ed46da1613576035b904739850452804ef)

大概可以？

**Comment by WordlessEcho** [comment]
> > 测试好了，要不要给Roboto也弄一份？
> > [b6daa5e](https://github.com/simonsmh/notocjk/commit/b6daa5ed46da1613576035b904739850452804ef)
> 
> 大概可以？

我不会写sed，要弄还得 @simonsmh 弄（跑
