### ISSUE TITLE
[Feature] Add updateJson support

### ISSUE THREAD

**Issue by simonsmh** [simonsmh/notocjk#35]

**Comment by simonsmh** [comment]
- `updateJson=https://cdn.jsdelivr.net/gh/simonsmh/notocjk@master/version.json`
- Maintainers should update json on each branch while bumping versions.
- Force refresh: `https://purge.jsdelivr.net/...`

**Comment by WordlessEcho** [comment]
> Package size exceeded the configured limit of 50 MB. Try https://github.com/simonsmh/notocjk/tree/master/version.json instead.

**Comment by simonsmh** [comment]
@WordlessEcho https://github.com/simonsmh/notocjk/blob/lite/version.json
