### ISSUE TITLE
Google Sans customization xml 检查出错

### ISSUE THREAD

**Issue by RayChanNya** [simonsmh/notocjk#36]
https://rayhere.lanzouw.com/iL4fLz4zugf
![Screenshot_20220123-000739_Pixel 启动器](https://user-images.githubusercontent.com/47655274/150646566-b808fdb7-e684-4746-abdd-52a56e4d9acb.png)

**Comment by RayChanNya** [comment]
旧版能用新版不能了（

**Comment by simonsmh** [comment]
有个地方写错了 我重新传一下（（

**Comment by RayChanNya** [comment]
> 有个地方写错了 我重新传一下（（

草（（

**Comment by simonsmh** [comment]
试一下21版 如果可以用记得告诉我（

**Comment by RayChanNya** [comment]
> 试一下21版 如果可以用记得告诉我（

卡Google了

**Comment by RayChanNya** [comment]
> 试一下21版 如果可以用记得告诉我（

还有，Google sans是偏粗的，感觉转换到普通字重应该加一点，具体的数值我比对之后在这个issues里发出来吧

**Comment by simonsmh** [comment]
https://github.com/simonsmh/notocjk/suites/5026894956/artifacts/148144314
麻烦再试一下这个（（（

**Comment by simonsmh** [comment]
我手头没有pixel机子，实在是测不了😂后面想个办法能不能模拟一下
这次是改customize.sh时突然想到会不会有其他oem做类似的修改，所以才加了这个判断的逻辑

**Comment by RayChanNya** [comment]
> 我手头没有pixel机子，实在是测不了😂后面想个办法能不能模拟一下

这玩意PE12也有，刷个完事了（
比如whyred之类的老机型也有适配的

**Comment by RayChanNya** [comment]
> 我手头没有pixel机子，实在是测不了😂后面想个办法能不能模拟一下 这次是改customize.sh时突然想到会不会有其他oem做类似的修改，所以才加了这个判断的逻辑

没问题了（
顺便，fork走更新一下我魔改的OPPO Sans（

**Comment by simonsmh** [comment]
感谢反馈（
