### ISSUE TITLE
在不借助magisk的情况下可能实现本模块的效果吗

### ISSUE THREAD

**Issue by M1sterXXL** [simonsmh/notocjk#38]
只是通过shizuku或者adb指令能达到目标吗

**Comment by xyf2018** [comment]
有可能。
该模块实现多字重是通过替换system分区的font.xml文件以及添加可变字体文件实现的（对于部分系统，如pixel和类原生还需要一些其他的更改）。
如果你可以在Recovery中直接对system分区进行文件的添加与替换，是可以实现同样的效果的。不过每次系统OTA升级后都需要重复一遍该操作，如果OTA是增量更新就不用了。

**Comment by WordlessEcho** [comment]
其实最主要的问题是Shizuku需要注入系统，要求对AOSP的代码比较熟悉，但我不会（

**Comment by diskdance** [comment]
也请看一下 #43

**Comment by nasbdh9** [comment]
续 https://github.com/simonsmh/notocjk/issues/43#issuecomment-1595814902
