### ISSUE TITLE
在 Android 13 QPR1 Beta 2 上导致锁屏数字变为 Roboto

### ISSUE THREAD

**Issue by 123Duo3** [simonsmh/notocjk#42]
关闭模块前![Screenshot_20221006-164618.png](https://user-images.githubusercontent.com/12569997/194267843-34615bc9-0ca5-4cde-beb0-287af4f378ad.png)
关闭模块后![Screenshot_20221006-165027.png](https://user-images.githubusercontent.com/12569997/194267912-ec667218-9908-4177-94af-98ad2d4f08f3.png)

**Comment by WordlessEcho** [comment]
可以把开启模块和关闭模块时的 `/etc/fonts.xml` 发出来看看吗？

**Comment by 123Duo3** [comment]
> 可以把开启模块和关闭模块时的 `/etc/fonts.xml` 发出来看看吗？

由于不支持上传 xml 作为附件，我把后缀名改为了 txt
麻烦了
[fonts_origin.txt](https://github.com/simonsmh/notocjk/files/9772395/fonts_origin.txt)
[fonts_modified.txt](https://github.com/simonsmh/notocjk/files/9772400/fonts_modified.txt)

**Comment by WordlessEcho** [comment]
请问您在升级系统后有重新安装过一次模块吗？另外我希望您能把 `/product/etc/fonts_customization.xml` 修改前后的文件都发出来

**Comment by 123Duo3** [comment]
> 请问您在升级系统后有重新安装过一次模块吗？另外我希望您能把 `/product/etc/fonts_customization.xml` 修改前后的文件都发出来

重新安装之后正常了，感谢您的帮助！但是我记得有重新安装过，下载目录里也放着当时下载的安装包...

**Comment by WordlessEcho** [comment]
> 另外我希望您能把 `/product/etc/fonts_customization.xml` 修改前后的文件都发出来

**Comment by 123Duo3** [comment]
[fonts_customization_original.txt](https://github.com/simonsmh/notocjk/files/9784651/fonts_customization_original.txt)
[fonts_customization_modified.txt](https://github.com/simonsmh/notocjk/files/9784652/fonts_customization_modified.txt)
这是已经正常之后的修改后的文件

**Comment by WordlessEcho** [comment]
看来是Android 13在fonts_customization.xml里新增的字体：
```xml
<family customizationType="new-named-family" name="google-sans-clock">
  <font>GoogleSansClock-Regular.ttf</font>
</family>
```
