### ISSUE TITLE
能否向 LinageOS 等常见 Android ROM 提交补丁？

### ISSUE THREAD

**Issue by diskdance** [simonsmh/notocjk#43]
鉴于 [Google Issue Tracker 中提交的问题](https://issuetracker.google.com/issues/186033995)迟迟不修复，如果能向 LineageOS（很多第三方 ROM 的上游）、GrapheneOS 以及 CalyxOS 等 ROM 直接提交字重补丁的话，就可以在不使用 Magisk 的情况下拥有完整的中文字重体验，不知道作者是否愿意实现？谢谢。

LineageOS: https://wiki.lineageos.org/contributing
GrapheneOS: https://grapheneos.org
CalyxOS: https://calyxos.org/

**Comment by WordlessEcho** [comment]
[186033995](https://issuetracker.google.com/issues/186033995)上次变化是5月9日，把归属从framwork改成text
回答你的问题，我和这些社区不熟，没法说服他们接受这样的补丁

**Comment by nasbdh9** [comment]
https://android-review.googlesource.com/c/platform/external/noto-fonts/+/2514316
从Android U (14) 开始不再需要修改（的样子）

**Comment by WordlessEcho** [comment]
> https://android-review.googlesource.com/c/platform/external/noto-fonts/+/2514316 从Android U (14) 开始不再需要修改（的样子）

他们只是改了目录结构，没有动其他的东西
https://cs.android.com/android/platform/superproject/+/27d80353f6c2ea53a9cc20e8c943307299cf9231:external/noto-fonts/notosanscjk/

**Comment by hustler-not-chatty** [comment]
昨天试了一下。

https://review.lineageos.org/q/topic:%2213-cjk-vf%22

但是把 VF 内置到系统并取代静态版有个问题，就是某些应用只会调用最细的字体来显示中文(例如 VLC 的字幕功能，游戏如 Muse Dash?，以及一堆 Qt 应用)，一时也找不到解决方案

**Comment by WordlessEcho** [comment]
> 昨天试了一下。
> 
> https://review.lineageos.org/q/topic:%2213-cjk-vf%22
> 
> 但是把 VF 内置到系统并取代静态版有个问题，就是某些应用只会调用最细的字体来显示中文(例如 VLC 的字幕功能，游戏如 Muse Dash?，以及一堆 Qt 应用)，一时也找不到解决方案

@hustler-not-chatty 像Android 13的Roboto一样，保留静态版本的字体给400字重用。本项目也是这么做的

**Comment by WordlessEcho** [comment]
忘记附上链接了，具体来说是这样，`fonts.xml`的第42行
https://android.googlesource.com/platform/frameworks/base/+/android13-qpr3-s9-release/data/fonts/fonts.xml#42

**Comment by hustler-not-chatty** [comment]
嗯，是可以，而且根据[这个 issue](https://github.com/notofonts/noto-cjk/issues/240)，现阶段也只能这么做了。

不过净增加 30MB 的系统空间占用，估计是没法接受的。🙃

**Comment by WordlessEcho** [comment]
> 嗯，是可以，而且根据[这个 issue](https://github.com/notofonts/noto-cjk/issues/240)，现阶段也只能这么做了。
> 
> 不过净增加 30MB 的系统空间占用，估计是没法接受的。🙃

Android 14已经不保留静态版本了，相信随着新系统的铺开这个问题会慢慢消失
