### ISSUE TITLE
装模块后⊛字符在firefox网页里显示为方块，但chrome里能正常显示

### ISSUE THREAD

**Issue by huyz-git** [simonsmh/notocjk#5]
MIUI10，Android8.0，Magisk17.1。
装模块前firefox一切正常，装了这个模块之后，⊛字符在firefox网页里显示为方块（至少百度搜索的搜索框里是这样），但firefox的地址栏和chrome均能正常显示。firefox的版本是61.0.2。
这是模块的问题还是firefox的问题呢

**Comment by simonsmh** [comment]
这次更新之后似乎修复了
