### ISSUE TITLE
在KernelSU上引起部分应用闪退

### ISSUE THREAD

**Issue by chtholly255** [simonsmh/notocjk#52]
在KernelSU上使用本模块引起Fennec(FireFox 衍生版)闪退

LineageOS 21 (Android 14) , KernelSU 11682

崩溃日志：
[fennec_fdroid-crash.log](https://github.com/simonsmh/notocjk/files/15189861/fennec_fdroid-crash.log)

**Comment by simonsmh** [comment]
使用KernelSU时需要禁用该默认卸载模块功能，因为模块需要针对字体文件进行全局变更，解析fonts找不到字体
Ref: https://kernelsu.org/zh_CN/guide/app-profile.html#%E5%8D%B8%E8%BD%BD%E6%A8%A1%E5%9D%97
Source: 
ASystemFontIterator_open: https://android.googlesource.com/platform/frameworks/base.git/+/refs/heads/android14-release/native/android/system_fonts.cpp#241
prepareFont: https://android.googlesource.com/platform/frameworks/minikin/+/refs/heads/android14-release/libs/minikin/Font.cpp#133

**Comment by xft233** [comment]
@simonsmh  您好，我也遇到了闪退问题。已经禁用了默认卸载模块功能。

Android 15 RisingOS (基于 LineageOS），KernelSuNext 12430
在之前的 RisingOS 6.2 正常，更新 RisingOS 6.3 之后出现部分软件闪退。不太清楚，是哪一方的问题。

[com.miHoYo.hkrpg_2025-03-18T22_40_04.654.log](https://github.com/user-attachments/files/19321392/com.miHoYo.hkrpg_2025-03-18T22_40_04.654.log)
