### ISSUE TITLE
Please support Noto Serif CJK on Andorid N+ in the next update

### ISSUE THREAD

**Issue by HoweChen** [simonsmh/notocjk#6]
Thank you very much!

p.s. How many weights are Noto Serif CJK would be supported? On the lite version, I only see two.

**Comment by simonsmh** [comment]
Noto Serif CJK has already been supported, full 7 weight is included, only in NotoCJK module.

**Comment by seasonyuu** [comment]
Noto Serif CJK has already been installed, but that "fallbackFor" option for the NotoSerifCJK doesn't work below Android P

**Comment by simonsmh** [comment]
@seasonyuu Sorry, system limitation.

**Comment by seasonyuu** [comment]
@simonsmh 我在尝试把 NotoSerif 直接替换成 NotoSerifCJK，在网页上直接调用 serif 字体时显示是好的，但是 App 中调用 serif 的话行高就变得很诡异。
![image](https://user-images.githubusercontent.com/8638535/47079822-f7ab4b80-d238-11e8-8e9a-008d0c530dc6.png)
![image](https://user-images.githubusercontent.com/8638535/47079837-009c1d00-d239-11e8-96aa-959b7713f5ae.png)

**Comment by simonsmh** [comment]
@seasonyuu 因为notocjk字体是双倍行高。
另外单独替换notoserif会只有单种样式。

**Comment by seasonyuu** [comment]
@simonsmh 并不是单纯的双倍行高问题吧，你看我截图里面，两行的文本里，并不是每一行的行高都是特别高的。看起来似乎是段间距被扩大了

**Comment by seasonyuu** [comment]
https://github.com/googlei18n/noto-cjk/issues/48 我的错

**Comment by WordlessEcho** [comment]
Noto Serif CJK 中的西文字形和 Noto Serif 一致么？
强行替换 Serif 可能会有问题

**Comment by WordlessEcho** [comment]
We use new feature “fallbackFor” to add serif CJK font which added in Android P.
More details (Chinese): [Android P Preview 1 中的字體變化](https://zhuanlan.zhihu.com/p/34924335)

**Comment by simonsmh** [comment]
西文好像是一样的。更多的问题是没有index，只有日文字形，就跟Linux上需要借用fontconfig指定中文字形是一个道理。

Wordless Echo <notifications@github.com> 于 2018年10月17日周三 下午10:41写道：

**Comment by simonsmh** [comment]
Closing for now.
